shellEmulator: true
trustPolicy: no-downgrade

packages:
  - packages/*

catalog:
  '@types/node': 26.1.1

allowBuilds:
  '@google/genai': true
  esbuild: true
  protobufjs: true
  tree-sitter-bash: true

minimumReleaseAgeExclude:
  - '@mzwing/oxc-config@0.1.4'
  - baseline-browser-mapping@2.11.1
  - race-expansion@5.0.8
  - flatted@3.4.3
  - brace-expansion@5.0.8
