name: Release

on:
  push:
    tags:
      - '*-v[0-9]+.[0-9]+.[0-9]+'
      - '*-v[0-9]+.[0-9]+.[0-9]+-*'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version
          check-latest: true
          registry-url: https://registry.npmjs.org/

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Prepare release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ github.ref_name }}
        run: pnpm run release:prepare

      - name: Publish to NPM
        env:
          NPM_TAG: ${{ steps.release.outputs.npm_tag }}
          PACKAGE_NAME: ${{ steps.release.outputs.package_name }}
        run: pnpm --filter "$PACKAGE_NAME" publish --access public --no-git-checks --tag "$NPM_TAG"

      - name: Publish GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NOTES_PATH: ${{ steps.release.outputs.release_notes_path }}
          RELEASE_TAG: ${{ github.ref_name }}
        run: pnpm run release:github
